---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: globex-keycloak-
  annotations:
    olm.providedAPIs: 'Keycloak.v2alpha1.k8s.keycloak.org,KeycloakRealmImport.v2alpha1.k8s.keycloak.org'
  name: rhbk-operator-group
spec:
  targetNamespaces:
    - {{ .Values.targetNamespaces }}
  upgradeStrategy: Default

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
spec:
  channel: stable-v22
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace